/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as MotorcyclesIndexRouteImport } from './routes/motorcycles.index'
import { Route as MotorcyclesBikeIdRouteImport } from './routes/motorcycles.$bikeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorcyclesIndexRoute = MotorcyclesIndexRouteImport.update({
  id: '/motorcycles/',
  path: '/motorcycles/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorcyclesBikeIdRoute = MotorcyclesBikeIdRouteImport.update({
  id: '/motorcycles/$bikeId',
  path: '/motorcycles/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/motorcycles/$bikeId': typeof MotorcyclesBikeIdRoute
  '/motorcycles/': typeof MotorcyclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/motorcycles/$bikeId': typeof MotorcyclesBikeIdRoute
  '/motorcycles': typeof MotorcyclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/motorcycles/$bikeId': typeof MotorcyclesBikeIdRoute
  '/motorcycles/': typeof MotorcyclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/jobs'
    | '/maintenance'
    | '/onboarding'
    | '/partner'
    | '/motorcycles/$bikeId'
    | '/motorcycles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/jobs'
    | '/maintenance'
    | '/onboarding'
    | '/partner'
    | '/motorcycles/$bikeId'
    | '/motorcycles'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/jobs'
    | '/maintenance'
    | '/onboarding'
    | '/partner'
    | '/motorcycles/$bikeId'
    | '/motorcycles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JobsRoute: typeof JobsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerRoute: typeof PartnerRoute
  MotorcyclesBikeIdRoute: typeof MotorcyclesBikeIdRoute
  MotorcyclesIndexRoute: typeof MotorcyclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorcycles/': {
      id: '/motorcycles/'
      path: '/motorcycles'
      fullPath: '/motorcycles/'
      preLoaderRoute: typeof MotorcyclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorcycles/$bikeId': {
      id: '/motorcycles/$bikeId'
      path: '/motorcycles/$bikeId'
      fullPath: '/motorcycles/$bikeId'
      preLoaderRoute: typeof MotorcyclesBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  JobsRoute: JobsRoute,
  MaintenanceRoute: MaintenanceRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerRoute: PartnerRoute,
  MotorcyclesBikeIdRoute: MotorcyclesBikeIdRoute,
  MotorcyclesIndexRoute: MotorcyclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
